-- Migration: Create Supabase Storage bucket for DROPONCE
-- Run this AFTER the main schema migration (20260910000000_create_files_schema.sql)
--
-- This creates a private "droponce-files" bucket in Supabase Storage.
-- All file access is via short-lived signed URLs generated by Edge Functions.
-- No direct public access is allowed.

-- Create the storage bucket (private, 50 MB per-file limit)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'droponce-files',
  'droponce-files',
  false,                     -- NOT public — all access via signed URLs only
  52428800,                  -- 50 MB per-file limit (50 * 1024 * 1024 bytes)
  null                       -- Allow all MIME types (Edge Function validates separately)
)
ON CONFLICT (id) DO UPDATE
  SET public = false,
      file_size_limit = 52428800;

-- Storage RLS: deny ALL direct access from anonymous or authenticated users.
-- Files can ONLY be accessed via Edge Functions using the service_role key,
-- which bypasses RLS entirely. This is intentional and correct.
CREATE POLICY "Deny direct anon read on droponce-files"
  ON storage.objects FOR SELECT
  TO anon
  USING (bucket_id != 'droponce-files');

CREATE POLICY "Deny direct anon upload to droponce-files"
  ON storage.objects FOR INSERT
  TO anon
  WITH CHECK (bucket_id != 'droponce-files');

CREATE POLICY "Deny direct auth read on droponce-files"
  ON storage.objects FOR SELECT
  TO authenticated
  USING (bucket_id != 'droponce-files');
